FROM tensorflow/tensorflow:1.15.5-gpu-py3-jupyter 

RUN apt update && apt install curl git -yq
RUN pip install --upgrade nbdev jupyterlab jupyter-client
RUN echo "alias ls='ls --color=auto'" >> /root/.bashrc

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install curl git cmake ack g++ python3-dev vim-youcompleteme tmux -yq
RUN apt-get install g++-8 -yq
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/qooba/vim-python-ide/master/setup.sh)"
RUN pip3 install qdi fastapi uvicorn jinja2 aiofiles python-multipart
ENV PYTHONPATH="/app:${PYTHONPATH}"
COPY ./models /models
CMD ["sh","-c", "jupyter lab --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.password='' --NotebookApp.token=''"]`
